import { Annotation, messagesStateReducer } from "@langchain/langgraph";
import { BaseMessage } from "@langchain/core/messages";
import { z } from "zod";

/**
 * Supported ad platform namespaces for skill resolution.
 */
export const PlatformTypeSchema = z.enum(["google_ads", "meta_ads"]);
export type PlatformType = z.infer<typeof PlatformTypeSchema>;

/**
 * Human-in-the-Loop lifecycle statuses for budget shifts.
 */
export const HumanApprovalStatusSchema = z.enum([
  "NOT_REQUIRED",
  "PENDING_APPROVAL",
  "APPROVED",
  "REJECTED",
]);
export type HumanApprovalStatus = z.infer<typeof HumanApprovalStatusSchema>;

/**
 * Schema for staged budget changes awaiting human approval or execution.
 */
export const ProposedBudgetShiftSchema = z.object({
  platform: z.enum(["google_ads", "meta_ads", "cross_platform"]),
  campaignId: z.string().min(1, "campaignId must not be empty"),
  campaignName: z.string().optional(),
  currentBudget: z.number().positive("currentBudget must be greater than zero"),
  proposedBudget: z.number().nonnegative("proposedBudget must be zero or positive"),
  changePercentage: z.number().describe("Percentage change e.g. -20 for 20% decrease"),
  reason: z.string().optional(),
  stagedAt: z.string(),
});
export type ProposedBudgetShift = z.infer<typeof ProposedBudgetShiftSchema>;

/**
 * Campaign budget details fetched across platforms.
 */
export interface CampaignBudgetInfo {
  id: string;
  name: string;
  dailyBudget: number;
  currency: string;
  status: "ENABLED" | "PAUSED";
  metricSummary?: {
    cpa?: number;
    roas?: number;
    spendLast7Days?: number;
    anomaliesDetected?: boolean;
  };
}

/**
 * Normalized platform budget state.
 */
export interface PlatformBudgetSummary {
  accountId: string;
  totalDailyBudget: number;
  currency: string;
  campaigns: CampaignBudgetInfo[];
  fetchedAt: string;
}

/**
 * Orchestrator planning metadata.
 */
export interface OrchestratorPlan {
  selectedPlatforms: PlatformType[];
  requiresBudgetPull: boolean;
  requiresAnalysis: boolean;
  activeSkillNamespaces: string[];
  rationale: string;
}

/**
 * Strictly typed LangGraph AgentState Annotation definition.
 */
export const AgentStateAnnotation = Annotation.Root({
  /**
   * Conversation message history managed via LangGraph reducer.
   */
  messages: Annotation<BaseMessage[]>({
    reducer: messagesStateReducer,
    default: () => [],
  }),

  /**
   * Client / organization identifier for multi-tenant isolation.
   */
  clientId: Annotation<string>({
    reducer: (prev, next) => next ?? prev,
    default: () => "default_client",
  }),

  /**
   * Platforms identified and selected by the Orchestrator.
   */
  targetPlatforms: Annotation<PlatformType[]>({
    reducer: (prev, next) => next ?? prev,
    default: () => [],
  }),

  /**
   * Flag indicating whether the orchestrator flagged ambiguity and requires user clarification.
   */
  clarificationNeeded: Annotation<boolean>({
    reducer: (prev, next) => next ?? prev,
    default: () => false,
  }),

  /**
   * Clarification question generated by the Orchestrator for ambiguous or underspecified requests.
   */
  clarificationQuestion: Annotation<string | null>({
    reducer: (prev, next) => next ?? prev,
    default: () => null,
  }),

  /**
   * Raw and aggregated budget data pulled across platforms.
   */
  platformBudgets: Annotation<Record<string, PlatformBudgetSummary>>({
    reducer: (prev, next) => ({ ...prev, ...next }),
    default: () => ({}),
  }),

  /**
   * Proposed budget shift staged by the analyst awaiting human approval or execution.
   */
  proposedBudgetShift: Annotation<ProposedBudgetShift | null>({
    reducer: (prev, next) => (next !== undefined ? next : prev),
    default: () => null,
  }),

  /**
   * Lifecycle status of the proposed budget shift.
   */
  humanApprovalStatus: Annotation<HumanApprovalStatus>({
    reducer: (prev, next) => next ?? prev,
    default: () => "NOT_REQUIRED",
  }),

  /**
   * Execution plan produced by the Orchestrator Agent.
   */
  orchestratorPlan: Annotation<OrchestratorPlan | null>({
    reducer: (prev, next) => next ?? prev,
    default: () => null,
  }),
});

/**
 * Inferred AgentState type for nodes and functions.
 */
export type AgentState = typeof AgentStateAnnotation.State;
export type AgentStateUpdate = typeof AgentStateAnnotation.Update;
